# Dockerfile for Jenkins build agent with Docker client
FROM gradle:jdk17

# Docker 클라이언트 설치
RUN apt-get update

RUN groupadd -g 1001 newdocker && usermod -aG newdocker root
# Jenkins가 Docker를 사용할 수 있도록 권한 설정
USER root

